const FETCH_ALL_CAKES = "FETCH_ALL_CAKES";
const ADD_CAKE = "ADD_CAKE";
const FETCH_ALL_FLOWERS = "FETCH_ALL_FLOWERS";
const ADD_FLOWER = "ADD_FLOWER";
const SET_CURRENT_ID = "SET_CURRENT_ID";

export {
    FETCH_ALL_CAKES,
    ADD_CAKE,
    FETCH_ALL_FLOWERS,
    ADD_FLOWER,
    SET_CURRENT_ID
}