const FETCH_ALL_CAKES = "FETCH_ALL_CAKES";
const ADD_CAKE = "ADD_CAKE";
const UPDATE_CAKE = "UPDATE_CAKE";

const FETCH_ALL_FLOWERS = "FETCH_ALL_FLOWERS";
const ADD_FLOWER = "ADD_FLOWER";
const UPDATE_FLOWER = "UPDATE_FLOWER";

const SET_CURRENT_ID = "SET_CURRENT_ID";
const SET_ID_CATEGORY = "SET_ID_CATEGORY";

export {
    FETCH_ALL_CAKES,
    ADD_CAKE,
    UPDATE_CAKE,
    FETCH_ALL_FLOWERS,
    ADD_FLOWER,
    UPDATE_FLOWER,
    SET_CURRENT_ID,
    SET_ID_CATEGORY
}