const FETCH_ALL_CAKES = "FETCH_ALL_CAKES";
const ADD_CAKE = "ADD_CAKE";
const UPDATE_CAKE = "UPDATE_CAKE";
const DELETE_CAKE = "DELETE_CAKE"

const FETCH_ALL_FLOWERS = "FETCH_ALL_FLOWERS";
const ADD_FLOWER = "ADD_FLOWER";
const UPDATE_FLOWER = "UPDATE_FLOWER";

const SET_CURRENT_ID = "SET_CURRENT_ID";
const SET_ID_CATEGORY = "SET_ID_CATEGORY";
const DELETE_FLOWER = "DELETE_FLOWER";

const CAKE_CATEGORY = "CAKE_CATEGORY";
const FLOWER_CATEGORY = "FLOWER_CATEGORY";
const SELECTED_PRODUCT = "SELECTED_PRODUCT";

const SET_SEARCH = "SET_SEARCH";

export {
    FETCH_ALL_CAKES,
    ADD_CAKE,
    UPDATE_CAKE,
    DELETE_CAKE,
    FETCH_ALL_FLOWERS,
    ADD_FLOWER,
    UPDATE_FLOWER,
    DELETE_FLOWER,
    SET_CURRENT_ID,
    SET_ID_CATEGORY,
    CAKE_CATEGORY,
    FLOWER_CATEGORY,
    SELECTED_PRODUCT,
    SET_SEARCH
}